# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyBlow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyBlow
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Action'

  target 'CurrencyBlowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyBlowUITests' do
    # Pods for testing
  end

end
